name: gasapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.1.8+11

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^19.2.1
  geocoding: ^4.0.0
  geolocator: ^14.0.1
  google_maps_flutter: ^2.12.3
  easy_localization: ^3.0.7
  get_it: ^8.0.3
  dio: ^5.7.0
  flutter_screenutil: ^5.9.3
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.16
  lottie: ^3.3.0
  flash: ^3.1.1
  image_picker: ^1.1.2
  pin_code_fields: ^8.0.1
  firebase_core: ^3.9.0
  shared_preferences: ^2.3.4
  flutter_widget_from_html: ^0.16.0
  dotted_border: ^3.0.1
  url_launcher: ^6.3.1
  photo_view: ^0.15.0
  flutter_rating_bar: ^4.0.1
  myfatoorah_flutter: ^3.2.3
  pdf: ^3.11.3
  printing: ^5.14.2
  package_info_plus: ^8.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6




flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/
    - assets/lottie/
    - assets/translations/ar-SA.json
    - assets/translations/en-US.json


  fonts:
    - family: SST-Arabic
      fonts:
        - asset: assets/fonts/alfont_com_AlFont_com_SST-Arabic-Roman.ttf
          weight: 700
        - asset: assets/fonts/alfont_com_AlFont_com_SST-Arabic-Roman.ttf
          weight: 600
        - asset: assets/fonts/alfont_com_AlFont_com_SST-Arabic-Roman.ttf
          weight: 500
        - asset: assets/fonts/alfont_com_AlFont_com_SST-Arabic-Roman.ttf
          weight: 400
        - asset: assets/fonts/alfont_com_AlFont_com_SST-Arabic-Roman.ttf
          weight: 300

# تكوين أيقونة التطبيق
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

# تكوين شاشة البداية
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  android_12:
    image: assets/images/splash.png
    icon_background_color: "#FFFFFF"
  fullscreen: true
  android: true
  ios: true
  web: false
  branding: assets/images/splash.png
  image_dark: assets/images/splash.png
  color_dark: "#FFFFFF"
  